config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  resources :groups
  resources :exercises do
    collection do
      get :search_for_named
    end
  end

  resources :events do
    member do
      put :add_role
      put :rm_role
    end
    collection do
      get :search
    end
  end
  get "/events/:id/*other" => "events#show" #if any txt is trailing id, send this route to events#show

  #stripe payment
  resources :charges, only: [:new, :create]

  #alias the "events" routes
  match '/e/*other',
    via: :all,
    to: redirect { |path_params, req|
      #We are matching /e from an absolute path. Thus, the first occurrence of '/e' is the one we want to substitute for '/events'. Sub the first and return
      req.original_url.sub('/e','/events')
    }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    #omniauth_callbacks: "user/omniauth_callbacks",
    passwords: "user/passwords",
    unlocks: "user/unlocks"
  }
  # resources :users, only: [:show]


  root to: "events#index"
  get ":page" => "pages#show"
end

app/models/event.rb
class Event < ApplicationRecord
    self.primary_key = :id
    before_create :set_id

    validates :name, presence: true, allow_blank: false
    validates :description, presence: true, allow_blank: false
    validates :min_participants, presence: true, allow_blank: false, numericality: { greater_than_or_equal_to: 0 }    
    validates :max_participants, presence: true, allow_blank: false, numericality: { greater_than_or_equal_to: :min_participants }    
    validates :start, presence: true
    validate  :start_is_in_future
    
    #user-event roles
    has_many :workers, dependent: :destroy
    has_many :participants, dependent: :destroy
    has_many :admins, dependent: :destroy
    has_one  :creator, dependent: :destroy

    #other data
    has_one :cost

    #exercise_instances
    has_many :exercise_instances, class_name: "Exercise::Instance"
    validates :exercise_instances, presence: true
    accepts_nested_attributes_for :exercise_instances, reject_if: :all_blank, allow_destroy: true
    
    #Address
    validates :address, presence: true, associated: true
    has_one :address, as: :addressable
    accepts_nested_attributes_for :address

    #Social Profile
    has_many :social_profiles, as: :shareable
    accepts_nested_attributes_for :social_profiles, reject_if: :all_blank, allow_destroy: true

    private
    
    def set_id
        self.id = ShortIds.new(Event)
    end

    def start_is_in_future
        if start <= Time.now
            errors.add(:start, "Must be in the future")
        end
    end
end

app/models/event/admin.rb
class Event::Admin < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates_uniqueness_of :event_id, :scope => :user_id, :message => "User is already administrating this event"
end

app/models/event/creator.rb
class Event::Creator < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates_uniqueness_of :event_id, :scope => :user_id, :message => "User already created this event"
end

app/models/event/participant.rb
class Event::Participant < ApplicationRecord
  enum event_role_type: [:admin, :creator, :worker, :participant]

  belongs_to :event
  belongs_to :user
  validates_uniqueness_of :event_id, :scope => :user_id, :message => "User is already participating in this event"

end

app/models/event/worker.rb
class Event::Worker < ApplicationRecord
  belongs_to :event
  belongs_to :user
  validates_uniqueness_of :event_id, :scope => :user_id, :message => "User is already working this event"
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show    
    #redirect to a readable URL
    readable_txt = @event.name.parameterize
    if ShortenableUrls.redirect_for_readability?(request, @event.id, readable_txt)
      redirect_to "/events/#{@event.id}/#{readable_txt}"
      return
    end
  end

  # GET /events/new
  def new
    @event = Event.new
    @address = @event.build_address
    @social_profile = @event.social_profiles.build
    @exercise_instances = @event.exercise_instances.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        #create the default event roles for the current_user that created the event
        @event.participants.create(user_id: current_user.id)
        Event::Creator.create(user_id: current_user.id, event_id: @event.id)

        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def rm_role    
    event = Event.find(params[:id])    
    model = select_role_model(params[:role])    
    model.find_by(event_id: event.id, user_id: current_user.id).destroy
    msg = "You are no longer participating."

    redirect_to event, notice: msg    
  end

  def add_role
    event = Event.find(params[:id])
    model = select_role_model(params[:role])
    model.create(event_id: event.id, user_id: current_user.id)
    msg = "You are now participating!"

    redirect_to event, notice: msg
  end

  def search
    local_events = search_for_local_events
    render json: local_events, only: [:id,:name,:description,:start], include: { address: { only: [:latitude,:longitude,:street_address] },  exercise_instances: {include: :exercise}}
  end
  
  private

  def search_for_local_events
    #check for required params before searching
    all_keys_present = params.has_key?(:sw_lat) and
    params.has_key?(:ne_lat) and
    params.has_key?(:sw_lng) and
    params.has_key?(:ne_lng) 
    if not all_keys_present
      return {}
    end
    
    start_datetime = Time.at(params[:start].to_i)
    end_datetime = Time.at(params[:end].to_i)
    
    #search database for local events using given params
    local_events = Event.includes(:address).references(:address)
      .where("latitude >= ? AND latitude <= ? AND longitude >= ? AND longitude <= ? AND 
        start >= ? AND start <= ?",       
          params[:sw_lat], params[:ne_lat], params[:sw_lng], params[:ne_lng],
          start_datetime, end_datetime,
          )
      .limit(50) # arbitrary limit, just so things don't get drowned out/too full on the map
  end

  def select_role_model(role)
    roles = Event::Participant.event_role_types
    case role
      when String(roles[:admin])
        model = Event::Admin
      when String(roles[:creator])
        model = Event::Creator
      when String(roles[:worker])
        model = Event::Worker
      when String(roles[:participant])
        model = Event::Participant
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
    @current_user_is_participating = @event.participants.find_by(user_id: current_user.id) != nil if user_signed_in?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event)
      .permit(:name, :description, 
        :cost,
        :start, 
        :min_participants, :max_participants,
        { address_attributes: [:address, :longitude, :latitude] },
        { social_profiles_attributes: [:id, :_destroy, :name, :url] },
        { exercise_instances_attributes: [:id, :_destroy, :distance, :duration, :exercise_name] }
    )
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event, validate: true do |f| %>
  <%= f.object.errors.full_messages.join(", ") if f.object.errors.any? %>

  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :start %>
  <%= f.input :min_participants, input_html: { min: '0' } %>
  <%= f.input :max_participants, input_html: { min: '0' } %>

  <%= f.simple_fields_for :address do |address| %>
    <%= render partial: 'shared/address/form', locals: {f: address} %>
  <% end %>



  <h2>Social Profiles</h2>

  <div id="social-profile-fields">
    <%= f.simple_fields_for :social_profiles do |social_profile| %>
      <%= render partial: 'shared/social_profile/form', locals: {f: social_profile} %>
    <% end %>
    <div><%= link_to_add_association 'add profile', f, :social_profiles, partial: 'shared/social_profile/form'%></div>
  </div>



  <h2>Workout</h2>

  <div id="workout-fields">
    <%= f.simple_fields_for :exercise_instances do |ex_inst| %>
      <%= render partial: 'shared/exercise_instance/form', locals: {f: ex_inst} %>
    <% end %>
    <div><%= link_to_add_association 'add exercise', f, :exercise_instances, partial: 'shared/exercise_instance/form'%></div>
  </div>
  


  <%= f.button :submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<!-- Google Maps Must be loaded -->
<% content_for :head do %>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCMh8-5D3mJSXspmJrhSTtt0ToGiA-JLBc&libraries=places"></script>
<% end %>

<script>
markerPos = new google.maps.LatLng(<%= @event.address.latitude %>,<%= @event.address.longitude %>);
</script>


<h2>
Participants: 
</h2>

<p><%= pluralize(@event.participants.count,'person') %> going to this event </p>

<p>

<% for participant in @event.participants %>
  <%= link_to participant.user.name, user_path(participant.user) %>
  <!-- Not right action, rm_role only adds/removes current user
  <% if current_user == @event.creator.user %>
    <%= link_to "X", 
        rm_role_event_path(role: Event::Participant.event_role_types[:participant]),
        method: :put, remote: true %>
  <% end %>
  -->
<% end %>
</p>

<p>
<% 
if user_signed_in? 
    if @current_user_is_participating %>
        <%= link_to "Drop out", 
            rm_role_event_path(role: Event::Participant.event_role_types[:participant]),
            method: :put, remote: true %>
    <% else %>
        <%= link_to "Sign Up", 
            add_role_event_path(role: Event::Participant.event_role_types[:participant]),
            method: :put, remote: true %>
    <%  end
end 
%>
</p>


<p>
Creator
<%= link_to @event.creator.user.name, user_path(@event.creator.user) %>
</p>

<%= 
#Event.reflect_on_all_associations.map{|x| x.class_name}.compact
%>

<p>Address: <%= @event.address.street_address %> </p>

<%= render partial: 'shared/social_profile/show', locals: {profiles: @event.social_profiles} %>

<div id="map"></div>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>